# Makefile for tests directory
SCRIPTSRC = 

default all:
	@: nothing to do in tests

clean:
	rm -rf logs depend

check test:
	mkdir -p logs
	: ------------------------- :
	:                           :
	: ------------------------- :

.PHONY: default all clean check test
