# Makefile for tests directory
SCRIPTSRC = 

default all:
	@: nothing to do in tests

clean:
	rm -rf log logs depend

check test:
	mkdir -p log
	: ------------------------- :
	:                           :
	: ------------------------- :

.PHONY: default all clean check test
