#! /usr/bin/env sh
# util/ccnshowFE
# 
# Part of the CCNx distribution.
#
# Copyright (C) 2009 Palo Alto Research Center, Inc.
#
# This work is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation.
# This work is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#

exec 2>/dev/null
for CCNDIR in "$@"; do 
  ccnls $CCNDIR/%FE | while read i j; do echo; echo $CCNDIR/%FE/$i; ccnget -c $CCNDIR/%FE/$i | ccn_ccnbtoxml -x - | xmllint --format -; done
done
