#!/usr/bin/env sh
D=`dirname "$0"`
D="${D:-.}"
: ${CCND_CAP:=50000}
export CCND_CAP
export PATH="$D"/agent:"$D"/lib:"$D"/udplink:"$D"/ccndc:$PATH
ccndsmoketest -t 55 kill recv 2>/dev/null
time ccnd "$@" &
ccndsmoketest `find "$HOME/.ccn/keyCache" -type f -name \*.ccnb`
S="$D"/ccn-start-udplink-`uname -n`.sh
test -f "$S" || echo '***' Please create $S script 'to start up udplink instance(s) for this machine'
test -f "$S" && sh "$S"
