#!/bin/sh
# validation/oops
# 
# Part of the CCNx distribution.
#
# Copyright (C) 2009 Palo Alto Research Center, Inc.
#
# This work is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation.
# This work is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
type xmllint
cat << EOF
****************
You may need to install a newer version of xmllint,
or change your PATH to find the right one.
For example, on Mac OS X, you can install xmllint using
macports, and set your path with
  export PATH=/opt/local/bin:\$PATH
****************
EOF
exit 1
