#!/bin/sh

JAVA_HOME=/usr
CCN_HOME_JAVA=${CCN_HOME_JAVA:-.}
JAVA=$JAVA_HOME/bin/java

CP1=$CCN_HOME_JAVA/*.jar
CP2=$CCN_HOME_JAVA/lib/*.jar

CP1=`echo $CP1 | sed "s/ /:/g"`
CP2=`echo $CP2 | sed "s/ /:/g"`

CLASSPATH=$CP1:$CP2

if [ $# = 0 ]
then
  echo "usage: ccn_repo [stop | <pathname>]"
else
  if [ "$1" = "stop" ]; then
	  if [ -n "$CCN_LOCAL_PORT" ]; then
	    $JAVA -cp $CLASSPATH -Dccn.agent.port=$CCN_LOCAL_PORT com.parc.ccn.network.daemons.repo.RepositoryDaemon -stop
	  else
	    $JAVA -cp $CLASSPATH com.parc.ccn.network.daemons.repo.RepositoryDaemon -stop
	  fi
  else
	  if [ -n "$CCN_LOCAL_PORT" ]; then
	      $JAVA -cp $CLASSPATH -Dccn.agent.port=$CCN_LOCAL_PORT com.parc.ccn.network.daemons.repo.RepositoryDaemon -start -root $*
	  else
	    $JAVA -cp $CLASSPATH com.parc.ccn.network.daemons.repo.RepositoryDaemon -start -root $*
	  fi
  fi
fi
