#!/bin/sh
# This munches the messages produced when ccnd_debug_bloom = 1
#
grep ^Bloom > /tmp/bloomstats.$$
cat /tmp/bloomstats.$$ | sort -u | cut -d , -f 1-3 | sort | uniq -c
echo ================================================
cat /tmp/bloomstats.$$ | sort -u | cut -d , -f 4 | sort | uniq -c | sort -n | grep sig | cut -f 1 -d = | uniq -c
rm -f /tmp/bloomstats.$$
