#!/bin/sh
: ${CCN_LOCAL_PORT:=2009}
export CCN_LOCAL_PORT
: ${CCND_DEBUG:=0}
export CCND_DEBUG

Fail () {
  echo '*** Failed' $* >&2
  exit 1
}

Cleanup () {
   ./ccndsmoketest kill 2>/dev/null
   wait
}

./ccndsmoketest kill 2>/dev/null
echo Starting ccnd with CCN_LOCAL_PORT=$CCN_LOCAL_PORT
./ccnd &

echo Making sure new ccnd is there
./ccndsmoketest 2>/dev/null || { sleep 1; ./ccndsmoketest || Fail; }

trap Cleanup 0

echo Populating ccnd with pre-signed data
./ccndsmoketest  -t 10 send fortunes.ccnb recv || Fail

echo Making anything.ccnb
../cmd/ccn_xmltoccnb -w - <<'END' > anything.ccnb
<Interest>
  <Name>
  </Name>
</Interest>
END

echo Trying for anything a few times
./ccndsmoketest -t 100 send anything.ccnb recv send anything.ccnb recv send anything.ccnb recv > anything.out || Fail
diff anything.ref anything.out || echo Diffs above might be OK, but have a look
MATCHES=`grep -c '^recv of' anything.out`
test $MATCHES = 3 || Fail Wrong number of matches, got $MATCHES expected 3

echo Testing contenthash
../cmd/ccn_xmltoccnb -w - <<'END' > contenthash.ccnb
<Interest>
  <Name>
    <Component ccnbencoding="text">local</Component>
    <Component ccnbencoding="text">test</Component>
    <Component ccnbencoding="text">fortunes</Component>
    <Component ccnbencoding="text">doubt</Component>
    <Component ccnbencoding="text">0</Component>
    <Component ccnbencoding="base64Binary">fGVA+Tyx5yIUgX4QiMWp0Swg7ud2tN/RrNw25HreUN4=</Component>
  </Name>
</Interest>
END

./ccndsmoketest -t 100 send contenthash.ccnb recv > contenthash.out || Fail
diff contenthash.ref contenthash.out || Fail contenthash.out does not match expected

echo Testing that fetch with bad hash does not succeed
../cmd/ccn_xmltoccnb -w - <<'END' > contentmishash.ccnb
<Interest>
  <Name>
    <Component ccnbencoding="text">local</Component>
    <Component ccnbencoding="text">test</Component>
    <Component ccnbencoding="text">fortunes</Component>
    <Component ccnbencoding="text">doubt</Component>
    <Component ccnbencoding="text">0</Component>
    <Component ccnbencoding="base64Binary">123A+Tyx5yIUgX4QiMWp0Swg7ud2tN/RrNw25HreUN4=</Component>
  </Name>
</Interest>
END
./ccndsmoketest -t 66 send contentmishash.ccnb recv | grep 'recv timed out' || Fail contentmishash
echo $0 TESTS PASSED
