cat <<EOF
Command/Utility Documentation
=============================

EOF
for i in "$@"; do
    j="`echo $i | sed -e 's/\.1\.html$/(1)/'`"
    echo ' - link:'$i'['$j']'
done
cat <<EOF

link:../index.html[Main Page]
//////////////////////////////////////
index.txt is generated by $0
//////////////////////////////////////
EOF
