'\" t
.\"     Title: ccncat
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.0 <http://docbook.sf.net/>
.\"      Date: 05/16/2013
.\"    Manual: \ \&
.\"    Source: \ \& 0.7.2
.\"  Language: English
.\"
.TH "CCNCAT" "1" "05/16/2013" "\ \& 0\&.7\&.2" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccncat \- Read streams of CCNx content and write to stdout
.SH "SYNOPSIS"
.sp
\fBccncat\fR [\-h] [\-d \fIflags\fR] [\-p \fIpipeline\fR] [\-s \fIscope\fR] [\-a] \fIccnxnames\fR\&...
.SH "DESCRIPTION"
.sp
The \fBccncat\fR utility retrieves content published under the \fIccnxnames\fR and writes it to stdout\&. The content must be published as a collection of CCNx Data in accordance with the naming conventions for segmented streams or files, optionally unversioned\&. For the default case of versioned content, \fBccncat\fR will retrieve the latest version available\&.
.sp
The \fIccnxnames\fR must be specified using the CCNx URI encoding syntax\&. For simple cases of ASCII name components this is just pathname syntax with / delimiters\&.
.SH "OPTIONS"
.PP
\fB\-h\fR
.RS 4
Generate the help message\&.
.RE
.PP
\fB\-d\fR \fIflags\fR
.RS 4
Specify the fetch debug flags which are the sum of the following: NoteGlitch = 1, NoteAddRem = 2, NoteNeed = 4, NoteFill = 8, NoteFinal = 16, NoteTimeout = 32, NoteOpenClose = 64
.RE
.PP
\fB\-p\fR \fIpipeline\fR
.RS 4
Set the size of the pipeline\&. Default 4\&.
.RE
.PP
\fB\-s\fR \fIscope\fR
.RS 4
Set the scope (integer) of the interests\&. Default unlimited\&. scope may be 0(cache), 1(local), 2(neighborhood), 3(unlimited)\&.
.RE
.PP
\fB\-a\fR
.RS 4
Allow stale data to be retrieved\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success, approximately, since the fetch client code doesn\(cqt currently indicate failure on stream reads\&.
.RE
.PP
\fB1\fR
.RS 4
Failure (syntax or usage error)
.RE
