'\" t
.\"     Title: ccnchat
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.0 <http://docbook.sf.net/>
.\"      Date: 01/28/2013
.\"    Manual: \ \&
.\"    Source: \ \& 0.7.1
.\"  Language: English
.\"
.TH "CCNCHAT" "1" "01/28/2013" "\ \& 0\&.7\&.1" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccnchat \- start (or join) a chatroom
.SH "SYNOPSIS"
.sp
\fBccnchat\fR \fIchatroomname\fR
.SH "DESCRIPTION"
.sp
The \fBccnchat\fR utility allows one to join an existing chat channel (or create a new one if that particular channel does not exist) specified by the \fIchatroomname\fR\&. The \fIchatroomname\fR must be preceded by ccnx:/
.sp
To run \fBccnchat\fR, you first need to start ccnd using the \fBccndstart(1)\fR command\&.
.SH "ENVIRONMENT"
.sp
Options for \fBccnchat\fR are set via environment variables\&.
.sp
CCNX_USER_NAME= friendlyname \- You\(cqll be known by this name in the chartroom\&. CCNX_DIR= /var/tmp/friendlyname/\&.ccnx \- If you are running multiple instances of \fBccnchat\fR on your machine, and you would like each instance to run under a different user (or friendly) name, then for each instance of \fBccnchat\fR, you will have to set the CNN_USER_NAME and CCNX_DIR environment variables\&.
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure (syntax or usage error; retrieval error)
.RE
.SH "AUTHOR"
.sp
Priya Mahadevan,
