'\" t
.\"     Title: ccngroup
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.0 <http://docbook.sf.net/>
.\"      Date: 05/16/2013
.\"    Manual: \ \&
.\"    Source: \ \& 0.7.2
.\"  Language: English
.\"
.TH "CCNGROUP" "1" "05/16/2013" "\ \& 0\&.7\&.2" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccngroup \- show and modify access control groups for access control of a CCNx content namespace\&.
.SH "SYNOPSIS"
.sp
\fBccngroup\fR [\-javaopts \fI<options>\fR] [\-debug \fI<portno>\fR] [\-as \fIkeystore\fR] \-list
.sp
\fBccngroup\fR [\-javaopts \fI<options>\fR] [\-debug \fI<portno>\fR] [\-as \fIkeystore\fR] \-listmembers \fIgroupFriendlyName\fR
.sp
\fBccngroup\fR [\-javaopts \fI<options>\fR] [\-debug \fI<portno>\fR] [\-as \fIkeystore\fR] \-create \fIgroupFriendlyName\fR \fIgroupMember\fR\&...
.sp
\fBccngroup\fR [\-javaopts \fI<options>\fR] [\-debug \fI<portno>\fR] [\-as \fIkeystore\fR] \-delete \fIgroupFriendlyName\fR
.sp
\fBccngroup\fR [\-javaopts \fI<options>\fR] [\-debug \fI<portno>\fR] [\-as \fIkeystore\fR] \-add \fIgroupFriendlyName\fR \fIgroupMemberToAdd\fR\&...
.sp
\fBccngroup\fR [\-javaopts \fI<options>\fR] [\-debug \fI<portno>\fR] [\-as \fIkeystore\fR] \-remove \fIgroupFriendlyName\fR \fIgroupMemberToRemove\fR\&...
.SH "DESCRIPTION"
.sp
The \fBccngroup\fR utility lists or modifies access control groups published with CCNx\&. Groups may be referenced in access control lists (ACLs) under the CCNx access control profile\&.
.sp
Groups have short, human\-readable "friendly" names by which they are identified with this tool, although the internal identifier for a group is a digest of a public key\&.
.SH "OPTIONS"
.PP
\fB\-as\fR \fIpathToKeystore\fR
.RS 4
Specifies a file path to a keystore; this is used for signing any newly\-created content\&. Applicable to all operations\&. The default keystore is used if this is not specified\&.
.RE
.PP
\fB\-list\fR
.RS 4
List the groups that exist\&.
.RE
.PP
\fB\-listmembers\fR \fIgroupFriendlyName\fR
.RS 4
List the members of the group
\fIgroupFriendlyName\fR\&.
.RE
.PP
\fB\-create\fR \fIgroupFriendlyName\fR \fIgroupMember\fR\&...
.RS 4
Create the group named
\fIgroupFriendlyName\fR
with initial members
\fIgroupMember\fR\&...
.RE
.PP
\fB\-delete\fR \fIgroupFriendlyName\fR
.RS 4
Delete the group named
\fIgroupFriendlyName\fR\&.
.RE
.PP
\fB\-add\fR \fIgroupFriendlyName\fR \fIgroupMemberToAdd\fR\&...
.RS 4
Add the
\fIgroupMemberToAdd\fR\&... members to the group
\fIgroupFriendlyName\fR\&.
.RE
.PP
\fB\-remove\fR \fIgroupFriendlyName\fR \fIgroupMemberToRemove\fR\&...
.RS 4
Remove the
\fIgroupMemberToRemove\fR\&... members from the group
\fIgroupFriendlyName\fR\&.
.RE
.PP
\fB\-debug\fR \fIportno\fR
.RS 4
Allows attachment of an eclipse remote debugger to the utility at the specified port number\&.
.RE
.PP
\fB\-javaopts\fR \fIoptions\fR
.RS 4
Allows use of arbitrary java properties or options with the utility\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure (syntax or usage error; retrieval error)
.RE
.SH "AUTHOR"
.sp
Philippe Golle
