'\" t
.\"     Title: ccnls
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.0 <http://docbook.sf.net/>
.\"      Date: 05/16/2013
.\"    Manual: \ \&
.\"    Source: \ \& 0.7.2
.\"  Language: English
.\"
.TH "CCNLS" "1" "05/16/2013" "\ \& 0\&.7\&.2" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccnls \- Attempts to list name components available at the next level of the hierarchy for a given CCNx name prefix\&.
.SH "SYNOPSIS"
.sp
\fBccnls\fR \fIccnxname\fR
.SH "DESCRIPTION"
.sp
The \fBccnls\fR utility lists name components available after the supplied CCNx name prefix, \fIccnxname\fR, for content objects that are cached in the local \fBccnd\fR\&.
.sp
This utility does not have explicit flags or options, but can be modified via environment variables\&. These include the scope of the generated interest (\fICCN_SCOPE\fR), the amount of time to wait between responses from \fBccnd\fR (\fICCN_LINGER\fR) and whether signature verification is desired (\fICCN_VERIFY\fR)\&.
.SH "OPTIONS"
.sp
The \fBccnls\fR utility does not have additional flags or options\&. Behavior can be changed by using the following two environment variables\&.
.sp
.if n \{\
.RS 4
.\}
.nf
CCN_SCOPE=
  Scope in generated interests (0, 1, 2)\&. The default is none specified\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
CCN_LINGER=
  Timeout for not receiving data\&.  The default is 0\&.5 seconds\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
CCN_VERIFY=
  If set and non\-empty, indicates that signature verification is required\&.
.fi
.if n \{\
.RE
.\}
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure (syntax or usage error; retrieval error)
.RE
.SH "AUTHOR"
.sp
Michael Plass
