'\" t
.\"     Title: ccnnamelist
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.0 <http://docbook.sf.net/>
.\"      Date: 01/28/2013
.\"    Manual: \ \&
.\"    Source: \ \& 0.7.1
.\"  Language: English
.\"
.TH "CCNNAMELIST" "1" "01/28/2013" "\ \& 0\&.7\&.1" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccnnamelist \- extract names from a file of ccnb encoded data
.SH "SYNOPSIS"
.sp
\fBccnnamelist\fR [\-h] [\fIfile\fR \fI\&...\fR]
.SH "DESCRIPTION"
.sp
The \fBccnnamelist\fR command prints on standard output a list of names from binary encoded data in one or more files\&.
.SH "OPTIONS"
.PP
\fB\-h\fR
.RS 4
Print the usage message\&.
.RE
.SH "ARGUMENTS"
.sp
The named files should contain ccnb\-encoded data\&. A "\-" in the file list indicates input from stdin\&. If no arguments are given input will be read from stdin\&.
.SH "OUTPUT"
.sp
A list of CCNx URI format names is produced on standard output\&. Any errors due to malformed input will result in a message on stderr
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fBnonzero\fR
.RS 4
Failure (syntax or usage error, file not found)
.RE
.SH "SEE ALSO"
.sp
\fBccn_splitccnb\fR(1)
.sp
Nick Briggs
