'\" t
.\"     Title: ccnrepoimport
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.0 <http://docbook.sf.net/>
.\"      Date: 05/16/2013
.\"    Manual: \ \&
.\"    Source: \ \& 0.7.2
.\"  Language: English
.\"
.TH "CCNREPOIMPORT" "1" "05/16/2013" "\ \& 0\&.7\&.2" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccnrepoimport \- Import file into Repository
.SH "SYNOPSIS"
.sp
\fBccnrepoimport\fR [\-timeout \fI<millis>\fR] [\-log \fI<level>\fR] \fIrepodir\fR \fIfilename\fR
.SH "DESCRIPTION"
.sp
The \fBccnrepoimport\fR utility is being deprecated and its use is discouraged\&.
.sp
The command merges Content Objects in a local file (\fIfilename\fR) into the Repository located in \fIrepodir\fR\&. Content Objects must be in the standard Repo form\&. The Repository located in \fIrepodir\fR must be currently served by an instance of ccnr; \fBccnrepoimport\fR will not work with ccn_repo\&.
.sp
\fIrepodir\fR is an absolute or relative pathname of the directory containing the Repository\&. \fIfilename\fR is an absolute or relative pathname of the file from which content is being imported\&. If relative, pathnames must be relative to the directory in which \fBccnrepoimport\fR is being executed\&.
.sp
If the command is accepted, the Repository attempts to open and parse the specified file\&. If there are no errors, Content Objects in the file that are not already in the Repository are added, and Content Objects that are already in the Repository are ignored\&.
.SH "OPTIONS"
.PP
\fB\-timeout\fR \fI<millis>\fR
.RS 4
Sets the timeout that will be used for importing the file, in milliseconds\&. This time depends on the length of the import file\&. If not specified, the default is 20000 (20 seconds)\&.
.RE
.PP
\fB\-log\fR \fI<level>\fR
.RS 4
Set the logging level\&.
\fI<level>\fR
must be an acceptable Logger level: either an integer or a level name (e\&.g\&., "SEVERE")\&. If not specified, the default is INFO\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure
.RE
.SH "AUTHOR"
.sp
Paul Rasmussen
