'\" t
.\"     Title: ccnrpolicyedit
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.0 <http://docbook.sf.net/>
.\"      Date: 01/28/2013
.\"    Manual: \ \&
.\"    Source: \ \& 0.7.1
.\"  Language: English
.\"
.TH "CCNRPOLICYEDIT" "1" "01/28/2013" "\ \& 0\&.7\&.1" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccnrpolicyedit \- edit policy\&.xml
.SH "SYNOPSIS"
.sp
\fBccnrpolicyedit\fR
.SH "DESCRIPTION"
.sp
The \fBccnrpolicyedit\fR command provides a convenient way to edit the policy associated with a repository instance\&.
.sp
The true repository policy is stored in a content object in the repo itself\&. It is encoded in ccnb format, which is not directly editable with the usual tools, such as a text editor\&. To cope with this, \fBccnrpolicyedit\fR works by translating the ccnb form to a normal text\-based xml encoding in a temporary copy, calling a text editor on this copy, and then translating back to ccnb before storing the updated policy in the repo\&.
.SH "OPTIONS"
.sp
None\&.
.SH "ARGUMENTS"
.sp
None\&.
.SH "ENVIRONMENT"
.sp
The value of \fBCCNR_GLOBAL_PREFIX\fR controls the repository instance that is to be configured\&. The usual way to set this is by editing ~/\&.ccnx/ccndrc The value of \fBEDITOR\fR may be used to specify what text editor should be called to do the actual editing\&. The default is \fBvi\fR\&.
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fBnonzero\fR
.RS 4
Failure (syntax or usage error, file not found)
.RE
.SH "FILES"
.sp
\fB~/\&.ccnx/ccnd\&.conf, ~/\&.ccnx/ccndrc, ~/\&.ccnx/repository/config\fR
.SH "AUTHOR"
.sp
Michael Plass
