'\" t
.\"     Title: ccnseqwriter
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.0 <http://docbook.sf.net/>
.\"      Date: 01/28/2013
.\"    Manual: \ \&
.\"    Source: \ \& 0.7.1
.\"  Language: English
.\"
.TH "CCNSEQWRITER" "1" "01/28/2013" "\ \& 0\&.7\&.1" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccnseqwriter \- Send data from stdin using ccn versioning and segmentation\&.
.SH "SYNOPSIS"
.sp
\fBccnseqwriter\fR [\-h] [\-b \fIblocksize\fR] [\-r] [\-s \fIscope\fR] [\-x \fIfreshness\fR] \fIccnx:/some/uri\fR
.SH "DESCRIPTION"
.sp
The \fBccnseqwriter\fR utility creates new ccn content using stdin as the source of data\&. The argument is a CCNx URI to be used for the newly signed data; appropriate versioning and segmentation will be added\&.
.sp
Unless the "\-r" option is used, no attempt is made to save the data in a repository, so if nothing expresses interest in the data, \fBccnseqwriter\fR will simply wait forever\&.
.SH "OPTIONS"
.PP
\fB\-h\fR
.RS 4
Print usage to stderr and exit\&.
.RE
.PP
\fB\-b\fR \fIblocksize\fR
.RS 4
Use given blocksize instead of the default (1024 bytes)\&. The maximum size allowed is 4096 bytes\&.
.RE
.PP
\fB\-r\fR
.RS 4
Generate a start\-write request to a repository\&. The start\-write is by default local scope, so only a local repository may answer\&. If there is no response to the start\-write request after 60s the command will fail with a diagnostic to stderr\&.
.RE
.PP
\fB\-s\fR \fIscope\fR
.RS 4
Use the given scope on the start\-write request (if \-r specified)\&.
\fIscope\fR
can be 1 (local), 2 (neighborhood), or 3 (unlimited)\&. Note that a scope of 3 is encoded as the absence of any scope in the interest\&.
.RE
.PP
\fB\-x\fR \fIfreshness\fR
.RS 4
Use the given freshness on all objects written\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure (diagnostic error written on stderr)
.RE
.SH "SEE ALSO"
.sp
\fBccnputfile\fR(1)
.SH "AUTHOR"
.sp
Michael Plass
