/*
 * Automatically generated by jrpcgen 1.0.7 on 12/6/07 10:26 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class DataBlock implements XdrAble {
    public int length;
    public byte [] data;

    public DataBlock() {
    }

    public DataBlock(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(length);
        xdr.xdrEncodeByteVector(data);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        length = xdr.xdrDecodeInt();
        data = xdr.xdrDecodeByteVector();
    }

}
// End of DataBlock.java
