/*
 * Automatically generated by jrpcgen 1.0.7 on 11/29/07 3:13 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class NameList implements XdrAble {
    public int count;
    public Name [] names;

    public NameList() {
    }

    public NameList(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(count);
        { int $size = names.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { names[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        count = xdr.xdrDecodeInt();
        { int $size = xdr.xdrDecodeInt(); names = new Name[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { names[$idx] = new Name(xdr); } }
    }

}
// End of NameList.java
