/*
 * Automatically generated by jrpcgen 1.0.7 on 12/6/07 10:26 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Name implements XdrAble {
    public NameComponent [] component;

    public Name() {
    }

    public Name(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = component.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { component[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = xdr.xdrDecodeInt(); component = new NameComponent[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { component[$idx] = new NameComponent(xdr); } }
    }

}
// End of Name.java
