/*
 * Automatically generated by jrpcgen 1.0.7 on 11/29/07 3:13 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class NameComponent implements XdrAble {
    public int length;
    public byte [] vals;

    public NameComponent() {
    }

    public NameComponent(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(length);
        xdr.xdrEncodeByteVector(vals);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        length = xdr.xdrDecodeInt();
        vals = xdr.xdrDecodeByteVector();
    }

}
// End of NameComponent.java
