/*
 * Automatically generated by jrpcgen 1.0.7 on 12/6/07 10:26 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class RepoTransport_TRANSPORTTOREPOPROG_ServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public RepoTransport_TRANSPORTTOREPOPROG_ServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public RepoTransport_TRANSPORTTOREPOPROG_ServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public RepoTransport_TRANSPORTTOREPOPROG_ServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(RepoTransport.TRANSPORTTOREPOPROG, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 1: {
                Name args$ = new Name();
                call.retrieveCall(args$);
                NameList result$ = Enumerate_1(args$);
                call.reply(result$);
                break;
            }
            case 2: {
                class XdrAble$ implements XdrAble {
                    public Name arg1;
                    public DataBlock arg2;
                    public void xdrEncode(XdrEncodingStream xdr)
                        throws OncRpcException, IOException {
                    }
                    public void xdrDecode(XdrDecodingStream xdr)
                        throws OncRpcException, IOException {
                        arg1 = new Name(xdr);
                        arg2 = new DataBlock(xdr);
                    }
                };
                XdrAble$ args$ = new XdrAble$();
                call.retrieveCall(args$);
                XdrInt result$ = new XdrInt(PutBlock_1(args$.arg1, args$.arg2));
                call.reply(result$);
                break;
            }
            case 3: {
                Name args$ = new Name();
                call.retrieveCall(args$);
                DataBlock result$ = GetBlock_1(args$);
                call.reply(result$);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract NameList Enumerate_1(Name arg1);

    public abstract int PutBlock_1(Name arg1, DataBlock arg2);

    public abstract DataBlock GetBlock_1(Name arg1);

}
// End of RepoTransport_TRANSPORTTOREPOPROG_ServerStub.java
