/*
 * Automatically generated by jrpcgen 1.0.7 on 12/6/07 10:26 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

/**
 * The class <code>RepoTransport_TRANSPORTTOREPOPROG_Client</code> implements the client stub proxy
 * for the TRANSPORTTOREPOPROG remote program. It provides method stubs
 * which, when called, in turn call the appropriate remote method (procedure).
 */
public class RepoTransport_TRANSPORTTOREPOPROG_Client extends OncRpcClientStub {

    /**
     * Constructs a <code>RepoTransport_TRANSPORTTOREPOPROG_Client</code> client stub proxy object
     * from which the TRANSPORTTOREPOPROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public RepoTransport_TRANSPORTTOREPOPROG_Client(InetAddress host, int protocol)
           throws OncRpcException, IOException {
        super(host, RepoTransport.TRANSPORTTOREPOPROG, 1, 0, protocol);
    }

    /**
     * Constructs a <code>RepoTransport_TRANSPORTTOREPOPROG_Client</code> client stub proxy object
     * from which the TRANSPORTTOREPOPROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public RepoTransport_TRANSPORTTOREPOPROG_Client(InetAddress host, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, RepoTransport.TRANSPORTTOREPOPROG, 1, port, protocol);
    }

    /**
     * Constructs a <code>RepoTransport_TRANSPORTTOREPOPROG_Client</code> client stub proxy object
     * from which the TRANSPORTTOREPOPROG remote program can be accessed.
     * @param client ONC/RPC client connection object implementing a particular
     *   protocol.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public RepoTransport_TRANSPORTTOREPOPROG_Client(OncRpcClient client)
           throws OncRpcException, IOException {
        super(client);
    }

    /**
     * Constructs a <code>RepoTransport_TRANSPORTTOREPOPROG_Client</code> client stub proxy object
     * from which the TRANSPORTTOREPOPROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public RepoTransport_TRANSPORTTOREPOPROG_Client(InetAddress host, int program, int version, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, 0, protocol);
    }

    /**
     * Constructs a <code>RepoTransport_TRANSPORTTOREPOPROG_Client</code> client stub proxy object
     * from which the TRANSPORTTOREPOPROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public RepoTransport_TRANSPORTTOREPOPROG_Client(InetAddress host, int program, int version, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, port, protocol);
    }

    /**
     * Call remote procedure Enumerate_1.
     * @param arg1 parameter (of type Name) to the remote procedure call.
     * @return Result from remote procedure call (of type NameList).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public NameList Enumerate_1(Name arg1)
           throws OncRpcException, IOException {
        NameList result$ = new NameList();
        client.call(RepoTransport.Enumerate_1, RepoTransport.TRANSPORTTOREPOVERSION, arg1, result$);
        return result$;
    }

    /**
     * Call remote procedure PutBlock_1.
     * @param arg1 parameter (of type Name) to the remote procedure call.
     * @param arg2 parameter (of type DataBlock) to the remote procedure call.
     * @return Result from remote procedure call (of type int).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public int PutBlock_1(Name arg1, DataBlock arg2)
           throws OncRpcException, IOException {
        class XdrAble$ implements XdrAble {
            public Name arg1;
            public DataBlock arg2;
            public void xdrEncode(XdrEncodingStream xdr)
                throws OncRpcException, IOException {
                arg1.xdrEncode(xdr);
                arg2.xdrEncode(xdr);
            }
            public void xdrDecode(XdrDecodingStream xdr)
                throws OncRpcException, IOException {
            }
        };
        XdrAble$ args$ = new XdrAble$();
        args$.arg1 = arg1;
        args$.arg2 = arg2;
        XdrInt result$ = new XdrInt();
        client.call(RepoTransport.PutBlock_1, RepoTransport.TRANSPORTTOREPOVERSION, args$, result$);
        return result$.intValue();
    }

    /**
     * Call remote procedure GetBlock_1.
     * @param arg1 parameter (of type Name) to the remote procedure call.
     * @return Result from remote procedure call (of type DataBlock).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public DataBlock GetBlock_1(Name arg1)
           throws OncRpcException, IOException {
        DataBlock result$ = new DataBlock();
        client.call(RepoTransport.GetBlock_1, RepoTransport.TRANSPORTTOREPOVERSION, arg1, result$);
        return result$;
    }

}
// End of RepoTransport_TRANSPORTTOREPOPROG_Client.java
