/*
 * Automatically generated by jrpcgen 1.0.7 on 3/14/08 5:06 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class RepoTransport_REPOTOTRANSPORTPROG_ServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public RepoTransport_REPOTOTRANSPORTPROG_ServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public RepoTransport_REPOTOTRANSPORTPROG_ServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public RepoTransport_REPOTOTRANSPORTPROG_ServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(RepoTransport.REPOTOTRANSPORTPROG, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 1: {
                Name args$ = new Name();
                call.retrieveCall(args$);
                XdrInt result$ = new XdrInt(RegisterInterest_1(args$));
                call.reply(result$);
                break;
            }
            case 2: {
                Name args$ = new Name();
                call.retrieveCall(args$);
                XdrInt result$ = new XdrInt(CancelInterest_1(args$));
                call.reply(result$);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract int RegisterInterest_1(Name arg1);

    public abstract int CancelInterest_1(Name arg1);

}
// End of RepoTransport_REPOTOTRANSPORTPROG_ServerStub.java
