/*
 * Automatically generated by jrpcgen 1.0.7 on 12/6/07 10:26 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
/**
 * A collection of constants used by the "RepoTransport" ONC/RPC program.
 */
public interface RepoTransport {
    public static final int Enumerate_1 = 1;
    public static final int CancelInterest_1 = 2;
    public static final int PutBlock_1 = 2;
    public static final int TRANSPORTTOREPOVERSION = 1;
    public static final int GetBlock_1 = 3;
    public static final int REPOTOTRANSPORTPROG = 390950;
    public static final int RegisterInterest_1 = 1;
    public static final int TRANSPORTTOREPOPROG = 390951;
    public static final int REPOTOTRANSPORTVERSION = 1;
}
// End of RepoTransport.java
