/*
 * Automatically generated by jrpcgen 1.0.7 on 11/29/07 3:13 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
/**
 * A collection of constants used by the "Repo2Transport" ONC/RPC program.
 */
public interface Repo2Transport {
    public static final int CancelInterest_1 = 2;
    public static final int REPOTOTRANSPORTVERSION = 1;
    public static final int REPOTOTRANSPORTPROG = 390950;
    public static final int RegisterInterest_1 = 1;
}
// End of Repo2Transport.java
