/*
 * Automatically generated by jrpcgen 1.0.7 on 11/29/07 3:13 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package com.parc.ccn.network.rpc;
/**
 * A collection of constants used by the "Transport2Repo" ONC/RPC program.
 */
public interface Transport2Repo {
    public static final int Enumerate_1 = 1;
    public static final int PutBlock_1 = 2;
    public static final int TRANSPORTTOREPOVERSION = 1;
    public static final int GetBlock_1 = 3;
    public static final int TRANSPORTTOREPOPROG = 390951;
}
// End of Transport2Repo.java
