#!/bin/sh
Commentize () {
  test -z $1 && echo && return 0
  echo '	/*' $1 '*/'
}
file ../../schema/tagname.csvdict >&2 || exit 1
tr ',' ' ' <../../schema/tagname.csvdict | while read i j k; do printf '    %s' "CCN_DTAG_$j = $i,"; Commentize "$k"; done
