#!/bin/sh
: ${CCN_LOCAL_PORT:=2009}
export CCN_LOCAL_PORT
: ${CCND_DEBUG:=0}
export CCND_DEBUG

Fail () {
  echo '*** Failed' $* >&2
  exit 1
}

Cleanup () {
   ./smoketestccnd kill 2>/dev/null
   wait
}

./smoketestccnd kill 2>/dev/null
echo Starting ccnd with CCN_LOCAL_PORT=$CCN_LOCAL_PORT
./ccnd &

echo Making sure new ccnd is there
./smoketestccnd 2>/dev/null || { sleep 1; ./smoketestccnd || Fail; }

trap Cleanup 0

echo Populating ccnd with pre-signed data
./smoketestccnd  -t 10 send fortunes.ccnb recv || Fail

echo Making anything.ccnb
../lib/ccn_xmltoccnb -w - <<'END' > anything.ccnb
<Interest>
  <Name>
  </Name>
</Interest>
END

echo Trying for anything a few times
./smoketestccnd -t 100 send anything.ccnb recv send anything.ccnb recv send anything.ccnb recv > anything.out || Fail
diff anything.ref anything.out || echo Diffs above might be OK, but have a look
MATCHES=`grep -c '^recv of' anything.out`
test $MATCHES = 3 || Fail Wrong number of matches, got $MATCHES expected 3

echo Testing contenthash
../lib/ccn_xmltoccnb -w - <<'END' > contenthash.ccnb
<Interest>
  <Name>
    <Component ccnbencoding="text">local</Component>
    <Component ccnbencoding="text">test</Component>
    <Component ccnbencoding="text">fortunes</Component>
    <Component ccnbencoding="text">doubt</Component>
    <Component ccnbencoding="text">0</Component>
    <Component ccnbencoding="base64Binary">fGVA+Tyx5yIUgX4QiMWp0Swg7ud2tN/RrNw25HreUN4=</Component>
  </Name>
</Interest>
END

./smoketestccnd -t 100 send contenthash.ccnb recv > contenthash.out || Fail
diff contenthash.ref contenthash.out || Fail

echo Testing that fetch with bad hash does not succeed
../lib/ccn_xmltoccnb -w - <<'END' > contentmishash.ccnb
<Interest>
  <Name>
    <Component ccnbencoding="text">local</Component>
    <Component ccnbencoding="text">test</Component>
    <Component ccnbencoding="text">fortunes</Component>
    <Component ccnbencoding="text">doubt</Component>
    <Component ccnbencoding="text">0</Component>
    <Component ccnbencoding="base64Binary">123A+Tyx5yIUgX4QiMWp0Swg7ud2tN/RrNw25HreUN4=</Component>
  </Name>
</Interest>
END
./smoketestccnd -t 66 send contentmishash.ccnb recv | grep 'recv timed out' || Fail contentmishash
echo $0 TESTS PASSED
