#!/bin/sh
# tests/extract_test_deps
# 
# Part of the CCNx distribution.
#
# Copyright (C) 2009 Palo Alto Research Center, Inc.
#
# This work is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation.
# This work is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# Script for extracting test deps for Makefile
# For maintainer use.
for i in test_*; do sed -n -e "s/^AFTER /$i/p" -e "s/^BEFORE /$i/p" $i; done
