#!/bin/sh
# javasrc/jrun
# 
# Part of the CCNx distribution.
#
# Copyright (C) 2009 Palo Alto Research Center, Inc.
#
# This work is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation.
# This work is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#

# This is a convenience script that uses a special ant target "run"
# to execute an arbitrary class with arguments from the command line.

CLASSNAME=$1
ant -quiet dumpclasspath
CPARG=`cat .antclasspath`
env CLASSPATH="$CPARG" java $*


