#!/bin/sh

JAVA_HOME=/usr
CCN_HOME_JAVA=${CCN_HOME_JAVA:-.}
JAVA=$JAVA_HOME/bin/java

CP1=$CCN_HOME_JAVA/*.jar
CP2=$CCN_HOME_JAVA/lib/*.jar

CP1=`echo $CP1 | sed "s/ /:/g"`
CP2=`echo $CP2 | sed "s/ /:/g"`

CLASSPATH=$CP1:$CP2
MEMORY=
DEBUG_PORT=
OUTPUT_FILE=
LOCAL_PORT=
DEBUG_DAEMON=
PROFILE_INFO=

if [ $# = 0 ]
then
  echo "usage: ccn_repo [stop <pid> | [interactive] <pathname> | signal <name> <pid>]"
else
  if [ ! "$CCN_LOCAL_PORT" = "" ]; then
  	  LOCAL_PORT="-Dccn.agent.port=$CCN_LOCAL_PORT"
  fi
  while [ $# -gt 2 ]; do
  	  if [ "$1" = "-memory" ]; then
  	      MEMORY="-Dccn.daemon.memory=$2"
  	      shift 2
  	  elif [ "$1" = "-debug" ]; then
  	      DEBUG_PORT="-Dccn.daemon.debug=$2"
  	      shift 2
  	  elif [ "$1" = "-output" ]; then
  	      OUTPUT_FILE="-Dccn.daemon.output=$2"
  	      shift 2
  	  elif [ "$1" = "-debug-daemon" ]; then
  	      DEBUG_DAEMON=" -Xrunjdwp:transport=dt_socket,address=$2,server=y,suspend=y";
  	      shift 2
  	  elif [ "$1" = "-profile" ]; then
  	      PROFILE_INFO="-Dccn.daemon.profile=$2";
  	      shift 2
  	  else
  	  	  break
  	  fi
  done
  if [ "$1" = "stop" ]; then
	  $JAVA -cp $CLASSPATH $LOCAL_PORT org.ccnx.ccn.impl.repo.RepositoryDaemon -stop $2
  elif [ "$1" = "signal" ]; then
          $JAVA -cp $CLASSPATH $LOCAL_PORT org.ccnx.ccn.impl.repo.RepositoryDaemon -signal $2 $3
  elif [ "$1" = "interactive" ]; then
          shift
	  $JAVA -cp $CLASSPATH $DEBUG_DAEMON $MEMORY $DEBUG_PORT $PROFILE_INFO $OUTPUT_FILE $LOCAL_PORT org.ccnx.ccn.impl.repo.RepositoryDaemon -interactive -root $*
  else
	  $JAVA -cp $CLASSPATH $DEBUG_DAEMON $MEMORY $DEBUG_PORT $PROFILE_INFO $OUTPUT_FILE $LOCAL_PORT org.ccnx.ccn.impl.repo.RepositoryDaemon -start -root $*
  fi
fi
